TC_09_06 | Verify unauthorized users can submit the Contact Us form
TheFocusTech/DomainQA pull request #100
Opened 2024-11-26 23:41 UTC by basinaviolet

…Us" form

2024-11-28 09:59 UTC, basinaviolet commented
The tests for the buttons have been fixed. Please, review the PR.

2024-11-28 16:56 UTC, Elgrueber commented on pom/pages/HelpContactUsPage.js
> +export const CONTACT_US_INPUT_NAME = {
please move all const variables to testdata file

2024-11-28 23:59 UTC, shadowlightcode approved these changes

2024-11-29 22:56 UTC, IrynaKolh requested changes

2024-11-30 20:59 UTC, closed without merging