TC_08_04_01
TheFocusTech/DomainQA pull request #36
Opened 2024-11-03 19:47 UTC by MariaKM

https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.333obp2smjp7

https://app.qase.io/project/01?case=15&suite=11

2024-11-03 19:52 UTC, SvetlanaMag approved these changes

2024-11-03 19:52 UTC, Volhabo approved these changes
Ok

2024-11-03 20:24 UTC, annaafanaseva commented on tests/08MyProfile.spec.js
> +            await expect(settingsNotificationsPage.notificationsTableRow).toHaveCount(countRows);
it seems you are retrieving countRows using rows.count(), but then comparing it back to the same settingsNotificationsPage.notificationsTableRow locator 🤔

2024-11-03 21:17 UTC, annaafanaseva commented on tests/08MyProfile.spec.js
> +            for (const checkbox of await settingsNotificationsPage.browserNotificationsCheckbox.all()) {
I don't think this step is working properly...

toBeChecked is missing '()' - so it's not being executed
'await' is missing before check() and expect
to uncheck checkbox 'uncheck()' should be used

not sure you are 'checking' the correct element.. input reflects the checkbox state but click should happen on element below it - need to debug..

2024-11-03 21:26 UTC, annaafanaseva requested changes
please make necessary changes

2024-11-08 13:58 UTC, annaafanaseva approved these changes

2024-11-08 14:26 UTC, annaafanaseva approved these changes

2024-11-08 14:27 UTC, merged