ED/tc 09 03 01
TheFocusTech/DomainQA pull request #48
Opened 2024-11-07 17:32 UTC by ElenaDetusheva

[TC_09_03_01](https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.jgxijwpv69l3)

2024-11-11 17:46 UTC, IrynaKolh approved these changes

2024-11-11 17:50 UTC, Elgrueber requested changes
Doesn't need to put locators in modal window class?

2024-11-18 16:05 UTC, IrynaKolh commented on pom/pages/HomePage.js
> +        this.advancedSearchHeading = this.page.getByText('Advanced search');
нужно удалить эти локаторы тк ты их перенесла в модалку

2024-11-19 15:57 UTC, ElenaDetusheva commented on pom/pages/HomePage.js
> +        this.advancedSearchHeading = this.page.getByText('Advanced search');
done

2024-11-19 15:58 UTC, Elgrueber approved these changes

2024-11-19 15:58 UTC, merged